services:

  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER  -p$$MYSQL_PASSWORD --silent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  api:
    image: ghcr.io/newtonperazzo/weather-analysis:stage
    restart: unless-stopped
    env_file:
      - .env.stage
    ports:
      - "8000:8080"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8080"

volumes:
  mysql_data: